### ISSUE TITLE
Stop propagate `withFilter` errors at the first `onFailure` handler.

### ISSUE THREAD

**Issue by cbowns** [troystribling/SimpleFutures#1]
This is a follow-on discussion to https://github.com/troystribling/BlueCap/issues/23. I'll write more here later.

**Comment by troystribling** [comment]
I am now thinking that this is not a good Idea since we would not be following the Scala Futures spec, http://docs.scala-lang.org/overviews/core/futures.html

In conclusion, if the original future is completed successfully then the returned future is completed with a mapped value from the original future. If the mapping function throws an exception the future is completed with that exception. If the original future fails with an exception then the returned future also contains the same exception. This exception propagating semantics is present in the rest of the combinators, as well.

Do you think you could determine where the error occurred by checking the error code? I think a better pattern would be to handle the error at the end of the call chain.

**Comment by cbowns** [comment]
Yeah, I figured this is in line with the Futures spec. (But sometimes specs aren't really oriented for real-world programming :stuck_out_tongue_winking_eye:)

I've been mitigating this in BlueCap by stringly-checking the error's description against the one thrown by the filter failure. A richer object from BlueCap would scratch that itch for me.

I agree with their sentiment: it's up to library authors to return a rich and detailed error object which explains what failure occurred where: was it in the most-recent futures evaluation, or is this propagation of an upstream failure?

**Comment by cbowns** [comment]
I'll move this back to BlueCap to hand back a better error object.
